language: cpp
compiler: gcc
dist: trusty

install:
  # Qt5
  - sudo apt-get install -qq libqt5webkit5-dev qtdeclarative5-dev
  - export QMAKE=/usr/lib/x86_64-linux-gnu/qt5/bin/qmake
  # Meschach
  - sudo apt-get install libmeschach-dev

script: 
  - qmake
  - make
  - ./edible -o test/primate.tree out.txt
  - cat out.txt
  - ./edible -o test/20170517_alignment_information_3.tree out.txt
  - cat out.txt
