######################################################################
# Automatically generated by qmake (3.0) Thu May 11 10:05:52 2017
######################################################################

TEMPLATE = app
TARGET = edible
INCLUDEPATH += . src src/Meschach

# Input
HEADERS += src/edible.h \
           src/gtr.h \
           src/new_models.h \
           src/variables.h \
           src/Meschach/err.h \
           src/Meschach/iter.h \
           src/Meschach/machine.h \
           src/Meschach/matlab.h \
           src/Meschach/matrix.h \
           src/Meschach/matrix2.h \
           src/Meschach/meminfo.h \
           src/Meschach/oldnames.h \
           src/Meschach/sparse.h \
           src/Meschach/sparse2.h \
           src/Meschach/zmatrix.h \
           src/Meschach/zmatrix2.h \
           src/Meschach/machines/Cray/machine.h \
           src/Meschach/machines/gcc/machine.h \
           src/Meschach/machines/Linux/machine.h \
           src/Meschach/machines/rs6000/machine.h \
           src/Meschach/machines/sgi/machine.h \
           src/Meschach/machines/sparc/machine.h
SOURCES += src/edible.c \
           src/gtr.c \
           src/llh.c \
           src/matrix.c \
           src/new_models.c \
           src/options.c \
           src/partial.c \
           src/random.c \
           src/read.c \
           src/tree.c \
           src/utility.c \
           src/Meschach/bdfactor.c \
           src/Meschach/bkpfacto.c \
           src/Meschach/chfactor.c \
           src/Meschach/copy.c \
           src/Meschach/dmacheps.c \
           src/Meschach/err.c \
           src/Meschach/extras.c \
           src/Meschach/fft.c \
           src/Meschach/fmacheps.c \
           src/Meschach/givens.c \
           src/Meschach/hessen.c \
           src/Meschach/hsehldr.c \
           src/Meschach/init.c \
           src/Meschach/iotort.c \
           src/Meschach/itertort.c \
           src/Meschach/ivecop.c \
           src/Meschach/lufactor.c \
           src/Meschach/machine.c \
           src/Meschach/matlab.c \
           src/Meschach/matop.c \
           src/Meschach/matrixio.c \
           src/Meschach/maxint.c \
           src/Meschach/meminfo.c \
           src/Meschach/memory.c \
           src/Meschach/memstat.c \
           src/Meschach/memtort.c \
           src/Meschach/mfunc.c \
           src/Meschach/mfuntort.c \
           src/Meschach/norm.c \
           src/Meschach/otherio.c \
           src/Meschach/pxop.c \
           src/Meschach/qrfactor.c \
           src/Meschach/schur.c \
           src/Meschach/solve.c \
           src/Meschach/sptort.c \
           src/Meschach/submat.c \
           src/Meschach/svd.c \
           src/Meschach/symmeig.c \
           src/Meschach/torture.c \
           src/Meschach/tutadv.c \
           src/Meschach/tutorial.c \
           src/Meschach/update.c \
           src/Meschach/vecop.c \
           src/Meschach/version.c \
           src/Meschach/ztorture.c \
           src/pcalc/pcalc.c \
           src/Meschach/machines/rs6000/machine.c
